<?php
require_once dirname(__DIR__) . '/config/bootstrap.php';

app_start_session();
if (!isset($_SESSION['email'])){
    header('Location: /login/login/login.php');
    exit();
}

// Check if the transferArray POST data is set
$transferArrayValue = null;
if (isset($_POST['transferArray'])) {
    $transferArrayJson = $_POST['transferArray'];
    // Decode the JSON string into a PHP array (optional)
    $transferArray = json_decode($transferArrayJson, true);

    // Pass the JSON data to JavaScript
    $transferArrayValue = json_encode($transferArray); // Encode back for JS
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>8-Puzzle Solver</title>
    <link rel="stylesheet" href="/solver/_8_puzzle.css">
    <link rel="stylesheet" href="/navbar/navbar.css">
    <script>
        // Pass the PHP variable to JavaScript if it exists
        <?php if ($transferArrayValue): ?>
            var transferArrayValue = <?php echo $transferArrayValue; ?>;
         // Alert the array in JavaScript
        <?php else: ?>
            var transferArrayValue = null;
        <?php endif; ?>
        window.onload=function() {
            displayBoard(transferArrayValue);}
            
    </script>
</head>
<body>
<?php include dirname(__DIR__) . '/navbar/navbar.php'; ?>
    <div class="container">
        <!-- <a href="../index.html"><button id="back">Back Home</button></a> -->
        <br><br>
        <div class="sudoku-container">
            <table>
                <tbody id="sudoku-grid"></tbody>
                <!--the grid wil be dynamically generated by JavaScript-->
            </table>
        </div>
        <br><br>
        <button onclick="randomize()">Randomize</button>
        <button onclick="reset()">Reset</button>
        <button onclick="solvePuzzle()">Solve Puzzle</button><br>
        <button class="btn" onclick="location.href='/game/_8_Puzzle_game.php'">GO BACK</button>
    </div>
    <div id="solution-tables"></div>
    <script src="/solver/_8_puzzle.js"></script>
</body>
</html>
